apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-clientes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-clientes
  template:
    metadata:
      labels:
        app: api-clientes
    spec:
      containers:
      - name: api-clientes
        image: mamazzei/api-clientes
        resources:
          limits:
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-clientes-service
spec:
  type: NodePort
  selector:
    app: api-clientes
  ports:
    - protocol: TCP     
      port: 5000
      targetPort: 5000
