apiVersion: apps/v1
kind: Deployment
metadata:
  name: barramento-de-eventos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barramento-de-eventos
  template:
    metadata:
      labels:
        app: barramento-de-eventos
    spec:
      containers:
      - name: barramento-de-eventos
        image: mamazzei/barramento-de-eventos
        resources:
          limits:
            memory: "256Mi"
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: barramento-de-eventos-service
spec:
  selector:
    app: barramento-de-eventos
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 10000
      targetPort: 10000