apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulta-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consulta
  template:
    metadata:
      labels:
        app: consulta
    spec:
      containers:
      - name: consulta
        image: mamazzei/consulta
        resources:
          limits:
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: consulta-service
spec:
  type: NodePort
  selector:
    app: consulta
  ports:
    - protocol: TCP     
      port: 6000
      targetPort: 6000
