apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts
spec:
  rules:
  - host: localhost # clientes.exemplo.com
    http:
      paths:
      - pathType: Prefix
        path: "/api-clientes"
        backend:
          service:
            name: api-clientes-service
            port:
              number: 5000
#  - host: "localhost" # pagamentos.exemplo.com
#    http:
      - pathType: Prefix
        path: "/api-pagamentos"
        backend:
          service:
            name: api-pagamentos-service
            port:
              number: 6000
#  - host: "localhost" # "pedidos.exemplo.com"
#    http:
      - pathType: Prefix
        path: "/api-pedidos"
        backend:
          service:
            name: api-pedidos-service
            port:
              number: 7000
#  - host: "localhost" # "produtos.exemplo.com"
#    http:
      - pathType: Prefix
        path: "/api-produtos"
        backend:
          service:
            name: api-produtos-service
            port:
              number: 9000

