apiVersion: apps/v1
kind: Deployment
metadata:
  name: observacoes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observacoes
  template:
    metadata:
      labels:
        app: observacoes
    spec:
      containers:
      - name: observacoes
        image: mamazzei/observacoes
        resources:
          limits:
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: observacoes-service
spec:
  type: NodePort
  selector:
    app: observacoes
  ports:
    - protocol: TCP     
      port: 5000
      targetPort: 5000
